### ISSUE TITLE
The contents of the source code do not match the paper

### ISSUE THREAD

**Issue by yeongsookim** [chsl/PLADE#4]
In the source code, DetectBoundaryPoints function is commented and there is no define DetectBoundaryPoints anywhere. so the filteredBoundaryPointsIndex is empty. As a result boundaryPointsOfEachPlane vector has 0 value to all elements and RansacExtract3Dline function does not work. So mainBoundaryIntersectionLines is empty.

source code:

```
    std::vector<int> boundaryPointsIndex, filteredBoundaryPointsIndex;
    // DetectBoundaryPoints(target_cloud,boundaryPointsIndex,0.35,0.35);
    filteredBoundaryPointsIndex = boundaryPointsIndex;
```

so the sentence of paper is not true.

> Similar to plane extraction, we use a RANSACstrategy to extract line segments from the boundary points[see Fig. 1(c)].

**Comment by LiangliangNan** [comment]
Indeed, as far as I can remember, there have been subsequent tests and developments since the publication of the paper. The code provided here may not exactly reflect these advancements, meaning the code is not an exact reference implementation of the paper anymore.

The detection of boundary points (followed by the extraction of lines from them to form descriptors) primarily comes into play when dealing with extremely incomplete point clouds. These situations arise when the point cloud fails to capture sufficient planar regions of a scene.  In practice, most point clouds typically contain sufficient planar regions to form descriptors for establishing correspondences. Besides, extracting planes tends to be more robust than extracting boundary lines. Thus, resorting to additional boundary lines only introduces redundant descriptors, which increases computational overhead without significant contribution to the registration process.

Nevertheless, extracting boundary lines can be advantageous in scenarios where extracting sufficient planes proves challenging, resulting in the inability to establish valid descriptors. However, such occurrences are relatively rare in most point cloud datasets.

**Comment by Navifra-Denny** [comment]
Thank you very much!

**Comment by yeongsookim** [comment]
Thank you very much!

**Comment by LiangliangNan** [comment]
Thank you for pointing out this. 
I have just clarified that the code has modifications since paper publication and added the following explanation in the ReadMe file:

`The main change is to omit the use of boundary lines. The detection of boundary lines to form descriptors primarily comes into play when dealing with extremely incomplete point clouds where the point cloud fails to capture sufficient planar regions of a scene (thus no descriptors could be constructed). Since point clouds typically contain more than sufficient planar regions to construct descriptors and extracting planes tends to be more robust than extracting boundary lines, detecting and utilizing boundary lines becomes unnecessary. Resorting to additional boundary lines only introduces redundant descriptors and increases computational overhead without significant contribution to the registration process.`
